### ISSUE TITLE
Eval出错

### ISSUE THREAD

**Issue by Hubotcoder** [truantmuse/chinese-qa-with-bert#15]
谢谢你提供的QA方案，我在Eval的时候报错了，我用的是windows 10，请问有关系吗？
Writing nbest to: ./chinese-qa-with-bert/output\nbest_predictions_.json
Traceback (most recent call last):
  File "D:/svn/chinese-qa-with-bert-88/bert_qa.py", line 527, in <module>
    main()
  File "D:/svn/chinese-qa-with-bert-88/bert_qa.py", line 516, in main
    result = evaluate(args, model, tokenizer, prefix=global_step)
  File "D:/svn/chinese-qa-with-bert-88/bert_qa.py", line 266, in evaluate
    results = evaluate_on_squad(evaluate_options)
  File "D:\svn\chinese-qa-with-bert-88\utils_squad_evaluate.py", line 360, in main
    dataset_json = json.load(f)
  File "C:\Users\Administrator\AppData\Local\conda\conda\envs\bert_qa\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 176: illegal multibyte sequence
输出的json文件这样的
"TRIAL_359_QUERY_0": [
        {
            "text": "\u8be5 \u5feb \u9910 \u5385 \u4e4b \u51b0 \u6dc7 \u6797 \u7c7b \u4ea7 \u54c1 \u6807 \u699c \u201c \u5012 \u676f \u5982 \u6d12 \uff0c \u6b64 \u676f \u514d \u8d39 \u201d",
            "probability": 0.21158930430817988,
            "start_logit": -6.036751747131348,
            "end_logit": -4.960316181182861
        },
        {
            "text": "\u8be5 \u5feb \u9910 \u5385 \u4e4b \u51b0 \u6dc7 \u6797 \u7c7b \u4ea7 \u54c1 \u6807 \u699c \u201c \u5012 \u676f \u5982 \u6d12",
            "probability": 0.1603287879058802,
            "start_logit": -6.036751747131348,
            "end_logit": -5.237736701965332
        },

**Comment by Hubotcoder** [comment]
> 谢谢你提供的QA方案，我在Eval的时候报错了，我用的是windows 10，请问有关系吗？ Writing nbest to: ./chinese-qa-with-bert/output\nbest_predictions_.json Traceback (most recent call last): File "D:/svn/chinese-qa-with-bert-88/bert_qa.py", line 527, in main() File "D:/svn/chinese-qa-with-bert-88/bert_qa.py", line 516, in main result = evaluate(args, model, tokenizer, prefix=global_step) File "D:/svn/chinese-qa-with-bert-88/bert_qa.py", line 266, in evaluate results = evaluate_on_squad(evaluate_options) File "D:\svn\chinese-qa-with-bert-88\utils_squad_evaluate.py", line 360, in main dataset_json = json.load(f) File "C:\Users\Administrator\AppData\Local\conda\conda\envs\bert_qa\lib\json__init__.py", line 293, in load return loads(fp.read(), UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 176: illegal multibyte sequence 输出的json文件这样的 "TRIAL_359_QUERY_0": [ { "text": "\u8be5 \u5feb \u9910 \u5385 \u4e4b \u51b0 \u6dc7 \u6797 \u7c7b \u4ea7 \u54c1 \u6807 \u699c \u201c \u5012 \u676f \u5982 \u6d12 \uff0c \u6b64 \u676f \u514d \u8d39 \u201d", "probability": 0.21158930430817988, "start_logit": -6.036751747131348, "end_logit": -4.960316181182861 }, { "text": "\u8be5 \u5feb \u9910 \u5385 \u4e4b \u51b0 \u6dc7 \u6797 \u7c7b \u4ea7 \u54c1 \u6807 \u699c \u201c \u5012 \u676f \u5982 \u6d12", "probability": 0.1603287879058802, "start_logit": -6.036751747131348, "end_logit": -5.237736701965332 },

Found the solution myself:
Change the code in utils_squad_evaluate.py, start at line 358:
`def main(OPTS):

    with open(OPTS.data_file, encoding='utf-8') as f:
        dataset_json = json.load(f)
        dataset = dataset_json['data']

    with open(OPTS.pred_file, encoding='utf-8') as f:
        preds = json.load(f)

    if OPTS.na_prob_file:
        with open(OPTS.na_prob_file, encoding='utf-8') as f:
            na_probs = json.load(f)`

**Comment by Hubotcoder** [comment]
> 谢谢你提供的QA方案，我在Eval的时候报错了，我用的是windows 10，请问有关系吗？ Writing nbest to: ./chinese-qa-with-bert/output\nbest_predictions_.json Traceback (most recent call last): File "D:/svn/chinese-qa-with-bert-88/bert_qa.py", line 527, in main() File "D:/svn/chinese-qa-with-bert-88/bert_qa.py", line 516, in main result = evaluate(args, model, tokenizer, prefix=global_step) File "D:/svn/chinese-qa-with-bert-88/bert_qa.py", line 266, in evaluate results = evaluate_on_squad(evaluate_options) File "D:\svn\chinese-qa-with-bert-88\utils_squad_evaluate.py", line 360, in main dataset_json = json.load(f) File "C:\Users\Administrator\AppData\Local\conda\conda\envs\bert_qa\lib\json__init__.py", line 293, in load return loads(fp.read(), UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 176: illegal multibyte sequence 输出的json文件这样的 "TRIAL_359_QUERY_0": [ { "text": "\u8be5 \u5feb \u9910 \u5385 \u4e4b \u51b0 \u6dc7 \u6797 \u7c7b \u4ea7 \u54c1 \u6807 \u699c \u201c \u5012 \u676f \u5982 \u6d12 \uff0c \u6b64 \u676f \u514d \u8d39 \u201d", "probability": 0.21158930430817988, "start_logit": -6.036751747131348, "end_logit": -4.960316181182861 }, { "text": "\u8be5 \u5feb \u9910 \u5385 \u4e4b \u51b0 \u6dc7 \u6797 \u7c7b \u4ea7 \u54c1 \u6807 \u699c \u201c \u5012 \u676f \u5982 \u6d12", "probability": 0.1603287879058802, "start_logit": -6.036751747131348, "end_logit": -5.237736701965332 },

Found the solution myself:
Change the code in utils_squad_evaluate.py, start at line 358:
`def main(OPTS):
    with open(OPTS.data_file, encoding='utf-8') as f:
        dataset_json = json.load(f)
        dataset = dataset_json['data']
    with open(OPTS.pred_file, encoding='utf-8') as f:
        preds = json.load(f)
    if OPTS.na_prob_file:
        with open(OPTS.na_prob_file, encoding='utf-8') as f:
            na_probs = json.load(f)`
